version: '3.8'  # You can omit this line if you prefer.

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8500"  # Map host port 8500 to container port 8500
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - STRIPE_API_KEY=your_stripe_api_key_here  # Pass environment variables if needed
